import type { Metadata } from "next";
import { ToolPageWrapper } from "@/components/tools/tool-page-wrapper";
import { ColorConverter } from "@/components/tools/color-converter";

export const metadata: Metadata = {
  title: "Color Converter & Palette — HEX, RGB, HSL with WCAG Contrast",
  description: "Free online color converter. Convert between HEX, RGB, and HSL. Check WCAG contrast ratios for accessibility and generate color palettes instantly.",
  alternates: { canonical: "/tools/color-converter" },
};

export default function Page() {
  return (
    <ToolPageWrapper
      name="Color Converter & Palette"
      slug="color-converter"
      description="Convert colors between HEX, RGB, and HSL formats. Check WCAG contrast ratios for accessibility compliance and generate harmonious color palettes."
      howToUse={[
        "Pick a color using the color picker or enter a HEX value.",
        "View the automatic conversion to RGB and HSL formats.",
        "Use the contrast checker to verify WCAG accessibility, and explore the generated palette.",
      ]}
      faqs={[
        { question: "What is WCAG contrast ratio?", answer: "WCAG (Web Content Accessibility Guidelines) defines minimum contrast ratios between text and background colors. Level AA requires 4.5:1 for normal text and 3:1 for large text. Level AAA requires 7:1 for normal text." },
        { question: "What's the difference between HEX, RGB, and HSL?", answer: "HEX uses a six-digit hexadecimal notation (#ff5733). RGB specifies Red, Green, and Blue values (0-255 each). HSL uses Hue (0-360°), Saturation (0-100%), and Lightness (0-100%) — HSL is often more intuitive for designers." },
        { question: "How is the palette generated?", answer: "The palette is generated by varying the lightness of the selected color in HSL space, creating a range from very light to very dark while preserving the hue and saturation. Click any swatch to copy its HEX value." },
      ]}
    >
      <ColorConverter />
    </ToolPageWrapper>
  );
}
