import type { Metadata } from "next";
import { ToolPageWrapper } from "@/components/tools/tool-page-wrapper";
import { CssFormatter } from "@/components/tools/css-formatter";

export const metadata: Metadata = {
  title: "CSS Minifier & Beautifier — Format CSS Online",
  description:
    "Minify CSS to reduce file size or beautify compressed CSS for readability. Instant formatting with syntax validation, all in your browser.",
  alternates: { canonical: "/tools/css-formatter" },
};

export default function Page() {
  return (
    <ToolPageWrapper
      name="CSS Minifier & Beautifier"
      slug="css-formatter"
      description="Paste any CSS and instantly minify it for production or beautify it for development. The minifier strips whitespace, comments, and redundant semicolons to shrink file size, while the beautifier adds consistent indentation and line breaks for easy reading. Everything runs locally in your browser — your stylesheets are never uploaded to a server."
      howToUse={[
        "Paste your CSS code into the input editor.",
        "Click Minify to compress the CSS or Beautify to expand and format it with consistent indentation.",
        "Copy the formatted output and use it in your project, or download it as a file.",
      ]}
      faqs={[
        {
          question: "What does CSS minification do?",
          answer:
            "CSS minification removes all unnecessary characters from your stylesheet without changing its functionality. This includes whitespace, line breaks, comments, and redundant semicolons. The result is a smaller file that downloads faster, reducing page load time and bandwidth usage — especially important for mobile users on slow connections.",
        },
        {
          question: "When should I beautify CSS instead of minifying it?",
          answer:
            "Beautifying (also called pretty-printing) is useful during development and debugging when you need to read and understand the styles. If you receive minified CSS from a third-party library or a production build and need to inspect or modify it, running it through the beautifier restores readable indentation and structure so you can work with it comfortably.",
        },
        {
          question: "How much file size reduction can I expect from minification?",
          answer:
            "Typical savings range from 10% to 30% depending on the original formatting and comment density. Heavily commented stylesheets or those generated by preprocessors like Sass can see even larger reductions. For maximum savings, combine minification with gzip or Brotli compression on your web server, which together can reduce CSS payload by 80% or more.",
        },
      ]}
    >
      <CssFormatter />
    </ToolPageWrapper>
  );
}
